var judgeList = [{
    'name': 'АШИРОВ АРТУР',
    'descr': 'HEAD OF DEVELOPMENT, TECH LEAD У TAIN UKRAINE',
    'photo': '/includes/images/Photos/Ashirov.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['PROG'],
}, {
    'name': 'ВАСЮК ТЕТЯНА',
    'descr': 'АСИСТЕНТ ВИПУСКОВОГО РЕЖИСЕРА ІНФОРМАЦІЙНОЇ СЛУЖБИ «ФАКТИ», ICTV',
    'photo': '/includes/images/Photos/Vasyuk.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['VID'],
}, {
    'name': 'АНДРЮЩЕНКО ОЛЕКСАНДР',
    'descr': 'User - Tester, Middleware Corezoid. Автор Чат - Бота для підготовки до ЗНО',
    'photo': '/includes/images/Photos/Andriushchenko.webp',
    'position': 'all',
    'fb': '',
    'noms': ['PROG', 'WEBAPP'],
}, {
    'name': 'БОГДАНОВИЧ АНДРІЙ',
    'descr': 'АРТ-ДИРЕКТОР FLAVA MOTION, МОУШН-ДИЗАЙНЕР, ВЕБ РОЗРОБНИК',
    'photo': '/includes/images/Photos/Bogdanovich.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['2DA', 'WEBCONST', 'WEBFRONT'],
}, {
    'name': 'ГРИЩЕНКО АНДРІЙ',
    'descr': 'ГРАФІЧНИЙ ДИЗАЙНЕР',
    'photo': '/includes/images/Photos/Grishenko.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['VID', '2DG', 'PHOTO'],
}, {
    'name': 'МЕРФІ СОЛОМІЯ',
    'descr': 'Фрілансер',
    'photo': '/includes/images/Photos/Merphy.webp',
    'position': 'mentor',
    'fb': '',
    'noms': ['VID'],
}, {
    'name': 'ДАВИДЕНКО КИРИЛО',
    'descr': 'Software engineer at Grammarly',
    'photo': '/includes/images/Photos/Davidenko.webp',
    'position': 'mentor',
    'fb': '',
    'noms': ['VID'],
}, {
    'name': 'ІРИНА КУЦЕВИЧ',
    'descr': 'Senior QA engineer, Namecheap',
    'photo': '/includes/images/Photos/Kuzevich.webp',
    'position': 'all',
    'fb': '',
    'noms': ['SCRATCH', 'WEBCONST', 'WEBFRONT'],
}, {
    'name': 'ГЛУШКО БОГДАН',
    'descr': 'CEO, Z-DIGITAL AGENCY',
    'photo': '/includes/images/Photos/Glushko.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['PROG', 'WEBAPP', 'WEBFRONT', 'PROGAPP', 'PROGTEXT'],
}, {
    'name': 'ДОБРОВОЛЬСЬКА ЛАРИСА',
    'descr': 'ВОЛОНТЕР ПРОЕКТУ CODECLUBUA, ВЧИТЕЛЬ ІНФОРМАТИКИ У ТЛУМАЦЬКІЙ ГІМНАЗІЇ',
    'photo': '/includes/images/Photos/Dobrovolckaya.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['SCRATCH'],
}, {
    'name': 'ЄГЕРОВ СЕРГІЙ',
    'descr': 'VFX PROJECT SUPERVISOR В ROOM8STUDIO. ВИКЛАДАЧ 3D-COAT ТА CONCEPT ART В GAMES ACADEMY',
    'photo': '/includes/images/Photos/Egorov.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['3D', 'GAMEDEV'],
}, {
    'name': 'ЄКИМЕНКО ОЛЕКСІЙ',
    'descr': 'ВІДЕОБЛОГЕР, КІНОКРИТИК, АСИСТЕНТ РЕЖИСЕРА ІНФОРМАЦІЙНОЇ СЛУЖБИ «ФАКТИ»',
    'photo': '/includes/images/Photos/Ekimenko.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['VID', 'PHOTO'],
}, {
    'name': 'ЄРЕМЕНКО АНТОН',
    'descr': 'FOUNDER ITALENT',
    'photo': '/includes/images/Photos/Anton.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['PROG', 'PROGAPP'],
}, {
    'name': 'ІЗМАЙЛОВА МАРІЯ',
    'descr': 'АРТ ДИРЕКТОР У КОМПАНІЇ NETENT',
    'photo': '/includes/images/Photos/Izmaylova.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['2DG'],
}, {
    'name': 'КОЛОМІЄЦЬ ІВАН',
    'descr': 'ФУЛСТЕК ВЕБ РОЗРОБНИК, ДИРЕКТОР З ІНФОРМАЦІЙНИХ ТЕХНОЛОГІЙ U-KNIGHT WEB STUDIO LLC',
    'photo': '/includes/images/Photos/Kolomiec.webp',
    'position': 'all',
    'fb': '',
    'noms': ['WEBAPP', 'WEBFRONT'],
}, {
    'name': 'КОРНІЄНКО ДМИТРО',
    'descr': 'КУРАТОР НАПРЯМКУ РОБОТОТЕХНІКА У BROBOTS',
    'photo': '/includes/images/Photos/Kornienko.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['PROGAPP'],
}, {
    'name': 'КРАВЦОВ СЕРГІЙ',
    'descr': 'ЗАСНОВНИК EVERGREEN.IT DEVELOPMENT, SUPPORT & SERVICE',
    'photo': '/includes/images/Photos/Kravcov.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['PROGAPP'],
}, {
    'name': 'КРИВИЧ СВІТЛАНА',
    'descr': 'КЕРІВНИК TAKE PRODUCTION',
    'photo': '/includes/images/Photos/Kryvych.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['VID', 'PHOTO', 'SOUND'],
}, {
    'name': 'КУБРАК ІРИНА',
    'descr': "ГРАФІЧНИЙ ДИЗАЙНЕР, ВИКЛАДАЧ КУРСІВ КОМП'ЮТЕРНА ГРАФІКА ТА ІНФОГРАФІКА",
    'photo': '/includes/images/Photos/Kubrak.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['2DG'],
}, {
    'name': 'ЛЮБІНЕЦЬ ОКСАНА',
    'descr': 'ВОЛОНТЕР ПРОЕКТУ CODE CLUB UA',
    'photo': '/includes/images/Photos/Lyubinec.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['SCRATCH'],
}, {
    'name': 'НЕЙМАН ЄВГЕН',
    'descr': 'PHP ПРОГРАМІСТ, DREAMSCAPE NETWORKS',
    'photo': '/includes/images/Photos/Neyman.webp',
    'position': 'all',
    'fb': '',
    'noms': ['PROG', 'WEBAPP', 'GAMEDEV'],
}, {
    'name': 'РУМЯНЦЕВ ОЛЕКСАНДР',
    'descr': 'ЗАСНОВНИК OLEKSFILM PRODUCTION, ВІДЕОБЛОГЕР, ВИКЛАДАЧ ШКОЛИ ТЕЛЕЖУРНАЛІСТИКИ MEDIASTART.SCHOOL',
    'photo': '/includes/images/Photos/Rumuancev.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['VID', 'PHOTO'],
}, {
    'name': 'САПРИКІНА ОЛЬГА',
    'descr': "КЕРIВНИК КОМП'ЮТЕРНОГО КЛУБУ ZX, ЦПР СВЯТОШИНСЬКОГО РАЙОНУ",
    'photo': '/includes/images/Photos/Saprykina.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['2DA', '2DG'],
}, {
    'name': 'СИВОКОНЬ ОЛЕКСІЙ',
    'descr': 'ДОСЛІДНИК МАШИННОГО НАВЧАННЯ',
    'photo': '/includes/images/Photos/Syvokon.webp',
    'position': 'all',
    'fb': '',
    'noms': ['PROGTEXT'],
}, {
    'name': 'ОСТРОВНИЙ ОЛЕКСАНДР',
    'descr': 'ФРОНТЕНД РОЗРОБНИК',
    'photo': '/includes/images/Photos/Ostrovniy.webp',
    'position': 'all',
    'fb': '',
    'noms': ['WEBFRONT'],
}, {
    'name': 'АНТОНІНА ВІННИК',
    'descr': 'Звукорежисер, фолі-артист, вокальний тренер, засновник Tonique Vocal School',
    'photo': '/includes/images/Photos/Vinnik.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['VID'],
}, {
    'name': 'ЛІЛІЯ ДІРЯВКА',
    'descr': 'FRONT-END РОЗРОБНИК, U-KNIGHT WEB STUDIO LLC',
    'photo': '/includes/images/Photos/Diriavka.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['WEBAPP', 'WEBFRONT', 'WEBCONST'],
}, {
    'name': 'ТЕБЕШЕВСЬКА МАРГАРИТА',
    'descr': 'РЕЖИСЕР АНІМАЦІНИХ ФІЛЬМІВ, ВИКЛАДАЧ КИЇВСЬКОГО УНІВЕРСИТЕТУ ІМ. БОРИСА ГРІНЧЕКА, ЕФІРНИЙ ДИЗАЙНЕР HROMADSKE.UA',
    'photo': '/includes/images/Photos/Tebeshevska.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['SOUND', '2DA'],
}, {
    'name': 'ФАРИСЕЙ КОСТЯНТИН',
    'descr': 'QA СПЕЦІАЛІСТ',
    'photo': '/includes/images/Photos/Farisey.webp',
    'position': 'all',
    'fb': '',
    'noms': ['GAMEDEV', 'SCRATCH'],
}, {
    'name': 'ТКАЧ ЛІЛІЯ',
    'descr': 'LEAD ARTIST, WARGAMING',
    'photo': '/includes/images/Photos/Tkach.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['3D'],
}, {
    'name': 'ШУБ РОДІОН',
    'descr': 'КЕРІВНИК АНІМАЦІЙНОЇ СТУДІЇ RIDNI ANIMATION',
    'photo': '/includes/images/Photos/Schub.webp',
    'position': 'judge',
    'fb': '',
    'noms': ['2DG', '2DA', 'VID'],
}, {
    'name': 'МІНДРА ДМИТРО',
    'descr': 'ENGINEERING MANAGER @ Grammarly',
    'photo': '/includes/images/Photos/Mindra.webp',
    'position': 'mentor',
    'fb': '',
    'noms': ['2DG', '2DA', 'VID'],
}, {
    'name': 'КАРКУНОВ ЯРОСЛАВ',
    'descr': 'SOFTWARE ENGINEER, Grammarly Inc.',
    'photo': '/includes/images/Photos/Karkunov.webp',
    'position': 'mentor',
    'fb': '',
    'noms': ['2DG', '2DA', 'VID'],
}, {
    'name': 'ЄЛЬЧАНІНОВ ДМИТРО',
    'descr': 'Доцент кафедри інформатики та інтелектуальної власності Національного технічного університету «Харківський політехнічний інститут»',
    'photo': '/includes/images/Photos/Elchaninov.webp',
    'position': 'mentor',
    'fb': '',
    'noms': ['2DG', '2DA', 'VID'],
}, {
    'name': 'АНДРЮЩЕНКО НАДІЯ',
    'descr': 'Співзасновниця  ІТ школи для дітей віком 5+ KidIT, Product Discovery Analyst в MacPaw',
    'photo': '/includes/images/Photos/Andrushchenko.webp',
    'position': 'mentor',
    'fb': '',
    'noms': ['2DG', '2DA', 'VID'],
}, ];

function compare(a, b) {
    if (a.name < b.name) {
        return -1;
    }
    if (a.name > b.name) {
        return 1;
    }
    return 0;
}

judgeList.sort(compare);
export {
    judgeList
};